INSERT INTO drivers (id,
                     prefix,
                     owner_first_name,
                     owner_last_name,
                     telephone_number,
                     address_line1,
                     address_line2,
                     city,
                     post_code,
                     vehicle_type,
                     engine_size,
                     additional_drivers,
                     commercial_purpose,
                     used_outside_the_registered_state,
                     current_value,
                     first_registered_date)
    VALUES (1,'Mr','John','Woo',123,'BakerStreet','ff','London','233-2','Coupe',1000,1,false,false,20000,'1990-01-01 00:00:01');

INSERT INTO drivers (id,
                     prefix,
                     owner_first_name,
                     owner_last_name,
                     telephone_number,
                     address_line1,
                     address_line2,
                     city,
                     post_code,
                     vehicle_type,
                     engine_size,
                     additional_drivers,
                     commercial_purpose,
                     used_outside_the_registered_state,
                     current_value,
                     first_registered_date)
VALUES (2,'Mrs','Anny','Woo',123,'BakerStreet','ff','London','233-2','Coupe',1000,1,false,false,20000,'1995-01-01 00:00:01');